version: "3.9" 
services:
  mysql:
    image: mysql:latest  
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: mysql-1 
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3334:3306"